_wandb:
    value:
        cli_version: 0.22.1
        e:
            hj0vq93469j6ec9i9nb21l8rvwn9jt7v:
                cpu_count: 6
                cpu_count_logical: 12
                cudaVersion: "12.7"
                disk:
                    /:
                        total: "1000202039296"
                        used: "686759972864"
                email: pisalboneryjay@gmail.com
                executable: e:\PD1ModelTrainings\DLenv\Scripts\python.exe
                git:
                    commit: f9ac7e6b0dd74ba9e3413f95a005e8342cee7d63
                    remote: https://github.com/eryyyj/WebAppBackend.git
                gpu: NVIDIA GeForce RTX 2060 SUPER
                gpu_count: 1
                gpu_nvidia:
                    - architecture: Turing
                      cudaCores: 2176
                      memoryTotal: "8589934592"
                      name: NVIDIA GeForce RTX 2060 SUPER
                      uuid: GPU-eaea0a4d-6955-ffc5-63c5-c5b8d630736f
                host: ELAI
                memory:
                    total: "17107861504"
                os: Windows-10-10.0.19045-SP0
                program: <python with no main file>
                python: CPython 3.13.7
                root: e:\PD1ModelTrainings\PD1ModelTrainingCodes
                startedAt: "2025-10-02T12:50:52.366241Z"
                writerId: hj0vq93469j6ec9i9nb21l8rvwn9jt7v
        m: []
        python_version: 3.13.7
        t:
            "1":
                - 1
            "2":
                - 1
            "3":
                - 2
                - 13
            "4": 3.13.7
            "5": 0.22.1
            "8":
                - 1
                - 3
            "12": 0.22.1
            "13": windows-amd64
